name: time-machine

services:
  app:
    image: mbentley/timemachine:smb
    environment:
      TM_USERNAME: ${TM_USERNAME:?err}
      TM_GROUPNAME: ${TM_GROUPNAME:?err}
      PASSWORD: ${PASSWORD:?err}
      TM_UID: ${TM_UID:?err}
      TM_GID: ${TM_GID:?err}
      SET_PERMISSIONS: ${SET_PERMISSIONS:?err}
      VOLUME_SIZE_LIMIT: ${VOLUME_SIZE_LIMIT:?err}
    ports:
      137:137/udp
      138:138/udp
      139:139
      445:445
    volumes:
      - ${TM_BACKUP_PATH:?err}:/opt/${TM_USERNAME:?err}
      - type: tmpfs
        target: /run/samba
    restart: unless-stopped
