name: media
services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    user: ${JLLFN_UID:-1000}:${JLLFN_GID:-1000}
    group_add:
      - {RENDER_GID:-1000}
    devices:
      - /dev/dri:/dev/dri
    networks:
      default:
      traefik-network:
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - type: bind
        source: ${MEDIA_LOCATION:?err}
        target: /media
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://play.${TS_TLD:?err}
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: Host(`play.${TS_TLD:?err}`)
      traefik.http.routers.jellyfin.entrypoints: web-secure
      # traefik.http.routers.jellyfin.middlewares: authentik-fa@file
      traefik.http.routers.jellyfin.tls: true
      traefik.http.routers.jellyfin.service: jellyfin
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096

    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  traefik-network:
    name: traefik-net
    external: true

volumes:
  jellyfin-config:
  jellyfin-cache: