services:
  app:
    image: adguard/adguardhome
    ports:
      - 53:53/udp # Plain DNS
      - 53:53/tcp # Plain DNS
      # - 67:67/udp # DHCP
      # - 68:68/udp # DHCP
      # - 30080:80/tcp # DNS over HTTPS
      # - 443:443/udp # DNS over HTTPS
      # - 443:443/tcp # DNS over HTTPS
      # - 784:784/udp # DNS over QUIC
      # - 853:853/udp # DNS over QUIC
      # - 853:853/tcp # DNS over TLS
      # - 30000:3000/tcp # Web
      # - 5443:5443/udp # DNSCrypt
      # - 5443:5443/tcp # DNSCrypt
      # - 8853:8853/udp # DNS over HTTPS
    volumes:
      - app-config:/opt/adguardhome/conf
      - app-workdir:/opt/adguardhome/work
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.adguard.entrypoints: web-secure
      traefik.http.routers.adguard.rule: Host(`home.${TS_TLD:?err}`) && (PathPrefix(`/adguard`) || HeaderRegexp(`Referer`, `.*/adguard/.*`))
      traefik.http.routers.adguard.middlewares: "authentik-fa@file"
      traefik.http.routers.adguard.tls: true
      traefik.http.routers.adguard.service: adguard
      traefik.http.services.adguard.loadbalancer.server.port: 80
      traefik.http.routers.adguard-install.entrypoints: web-secure
      traefik.http.routers.adguard-install.rule: Host(`home.${TS_TLD:?err}`) && (PathPrefix(`/adguard-install`) || HeaderRegexp(`Referer`,`.*/adguard-install/.*`))
      traefik.http.routers.adguard-install.middlewares: "authentik-fa@file"
      traefik.http.routers.adguard-install.tls: true
      traefik.http.routers.adguard-install.service: adguard-install
      traefik.http.services.adguard-install.loadbalancer.server.port: 3000

volumes:
  app-config:
  app-workdir:

networks:
  default:
    external: true
    name: traefik-net
