name: tailscale

x-ts-common: &ts-common
  image: docker.io/tailscale/tailscale:latest
  restart: unless-stopped
  cap_add:
    - net_admin
  devices:
    - /dev/net/tun:/dev/net/tun
  dns:
    - 1.1.1.1
    - 100.100.100.100
  environment: &ts-common-env
    TS_AUTH_ONCE: ${TS_AUTHONCE:-true}
    TS_AUTHKEY: ${TS_AUTHKEY:?err}
    TS_STATE_DIR: ${TS_STATE_DIR:-/var/lib/tailscale}
    TS_DEST_IP: ${TRAEFIK_IP:?err}
    TS_USERSPACE: ${TS_USERSPACE:-false}
    TS_TLD: ${TS_TLD:?err}
  healthcheck:
    test: tailscale cert --cert-file /ts-certs/$${TS_HOSTNAME}.$${TS_TLD}.crt --key-file /ts-certs/$${TS_HOSTNAME}.$${TS_TLD}.key $${TS_HOSTNAME}.$${TS_TLD}
    interval: 86400s
    timeout: 300s
    retries: 3
    start_period: 10s

services:
  auth:
    <<: *ts-common
    hostname: auth
    environment:
      <<: *ts-common-env
      TS_SOCKET: /ts-sockets/tailscaled-auth.sock
      TS_HOSTNAME: auth
    volumes:
      - ts-sockets:/ts-sockets
      - ts-certs:/ts-certs
      - ts-state-auth:/var/lib/tailscale
  home:
    <<: *ts-common
    hostname: home
    environment:
      <<: *ts-common-env
      TS_SOCKET: /ts-sockets/tailscaled-home.sock
      TS_HOSTNAME: home
    volumes:
      - ts-sockets:/ts-sockets
      - ts-certs:/ts-certs
      - ts-state-home:/var/lib/tailscale
  monitoring:
    <<: *ts-common
    hostname: monitoring
    environment:
      <<: *ts-common-env
      TS_SOCKET: /ts-sockets/tailscaled-monitoring.sock
      TS_HOSTNAME: monitoring
    volumes:
      - ts-sockets:/ts-sockets
      - ts-certs:/ts-certs
      - ts-state-monitoring:/var/lib/tailscale
  photos:
    <<: *ts-common
    hostname: photos
    environment:
      <<: *ts-common-env
      TS_SOCKET: /ts-sockets/tailscaled-photos.sock
      TS_HOSTNAME: photos
    volumes:
      - ts-sockets:/ts-sockets
      - ts-certs:/ts-certs
      - ts-state-photos:/var/lib/tailscale
  play:
    <<: *ts-common
    hostname: play
    environment:
      <<: *ts-common-env
      TS_SOCKET: /ts-sockets/tailscaled-play.sock
      TS_HOSTNAME: play
    volumes:
      - ts-sockets:/ts-sockets
      - ts-certs:/ts-certs
      - ts-state-play:/var/lib/tailscale
  search:
    <<: *ts-common
    hostname: search
    environment:
      <<: *ts-common-env
      TS_SOCKET: /ts-sockets/tailscaled-search.sock
      TS_HOSTNAME: search
    volumes:
      - ts-sockets:/ts-sockets
      - ts-certs:/ts-certs
      - ts-state-search:/var/lib/tailscale

volumes:
  ts-certs:
    name: tailscale-certs
  ts-sockets:
    name: tailscale-sockets
  ts-state-auth:
  ts-state-home:
  ts-state-monitoring:
  ts-state-photos:
  ts-state-play:
  ts-state-search:

networks:
  default:
    external: true
    name: traefik-net
