tls:
  stores:
    default:
      defaultCertificate:
        certFile: '/ts-certs/home.{{ env "TS_TLD" }}.crt'
        keyFile: '/ts-certs/home.{{ env "TS_TLD" }}.key'
  certificates:
    - certFile: '/ts-certs/auth.{{ env "TS_TLD" }}.crt'
      keyFile: '/ts-certs/auth.{{ env "TS_TLD" }}.key'
    - certFile: '/ts-certs/home.{{ env "TS_TLD" }}.crt'
      keyFile: '/ts-certs/home.{{ env "TS_TLD" }}.key'
    - certFile: '/ts-certs/monitoring.{{ env "TS_TLD" }}.crt'
      keyFile: '/ts-certs/monitoring.{{ env "TS_TLD" }}.key'
    - certFile: '/ts-certs/photos.{{ env "TS_TLD" }}.crt'
      keyFile: '/ts-certs/photos.{{ env "TS_TLD" }}.key'
    - certFile: '/ts-certs/play.{{ env "TS_TLD" }}.crt'
      keyFile: '/ts-certs/play.{{ env "TS_TLD" }}.key'
    - certFile: '/ts-certs/plex.{{ env "TS_TLD" }}.crt'
      keyFile: '/ts-certs/plex.{{ env "TS_TLD" }}.key'
    - certFile: '/ts-certs/search.{{ env "TS_TLD" }}.crt'
      keyFile: '/ts-certs/search.{{ env "TS_TLD" }}.key'
