api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: 0s
  web-secure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: 0s
    http:
      middlewares:
        - strip-prefix@file
        # - error-pages@docker
      tls: true

serversTransport:
  insecureSkipVerify: true

metrics:
  prometheus:
    manualRouting: true
    addEntrypointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-net
    watch: true
  file:
    directory: /dynamic
    watch: true

